// frontend-react/src/components/FormularioReceta.tsx
import React, { useState, useEffect } from 'react';
import { Recipe } from '../common/Interfaces';
import { recipeService } from '../services/recipeService';
import './FormularioReceta.css';

interface FormularioRecetaProps {
  receta?: Recipe | null;
  onGuardada: (mensaje: string) => void;
  onCerrada: () => void;
}

export const FormularioReceta: React.FC<FormularioRecetaProps> = ({ receta, onGuardada, onCerrada }) => {
  const [formulario, setFormulario] = useState<Partial<Recipe>>({
    title: '',
    description: '',
    ingredients: '',
    preparationTime: 0,
    servings: 1,
    difficulty: 'medium',
    category: undefined,
    isVegan: false,
    isGlutenFree: false,
    rating: 0,
    imageUrl: ''
  });

  const [cargando, setCargando] = useState(false);
  const [mensajeError, setMensajeError] = useState<string | null>(null);
  const [erroresValidacion, setErroresValidacion] = useState<Record<string, string>>({});

  useEffect(() => {
    console.log('📝 FormularioReceta montado con receta:', receta);
    if (receta && receta._id) {
      console.log('✏️ Modo EDICIÓN');
      setFormulario(receta);
    } else {
      console.log('🆕 Modo CREAR');
      setFormulario({
        title: '',
        description: '',
        ingredients: '',
        preparationTime: 0,
        servings: 1,
        difficulty: 'medium',
        category: undefined,
        isVegan: false,
        isGlutenFree: false,
        rating: 0,
        imageUrl: ''
      });
    }
  }, [receta]);

  const validar = (): boolean => {
    const nuevosErrores: Record<string, string> = {};

    if (!formulario.title || formulario.title.length < 3) {
      nuevosErrores.title = 'El título debe tener al menos 3 caracteres';
    }

    if (!formulario.description || formulario.description.length < 10) {
      nuevosErrores.description = 'La descripción debe tener al menos 10 caracteres';
    }

    if (!formulario.ingredients) {
      nuevosErrores.ingredients = 'Los ingredientes son requeridos';
    }

    if (!formulario.preparationTime || formulario.preparationTime < 1 || formulario.preparationTime > 1000) {
      nuevosErrores.preparationTime = 'Tiempo de preparación debe estar entre 1 y 1000 minutos';
    }

    if (!formulario.servings || formulario.servings < 1) {
      nuevosErrores.servings = 'Las porciones deben ser mínimo 1';
    }

    if (!formulario.category) {
      nuevosErrores.category = 'La categoría es requerida';
    }

    if (formulario.rating! < 0 || formulario.rating! > 5) {
      nuevosErrores.rating = 'El rating debe estar entre 0 y 5';
    }

    setErroresValidacion(nuevosErrores);
    return Object.keys(nuevosErrores).length === 0;
  };

  const alEnviar = async (e: React.FormEvent) => {
    e.preventDefault();
    console.log('💾 Enviando formulario...');

    if (!validar()) {
      setMensajeError('Por favor completa todos los campos correctamente');
      return;
    }

    setCargando(true);
    setMensajeError(null);

    try {
      if (receta && receta._id) {
        // Modo edición
        console.log('✏️ Actualizando receta:', receta._id);
        await recipeService.updateRecipe(receta._id, formulario);
        onGuardada('✅ Receta actualizada exitosamente');
      } else {
        // Modo crear
        console.log('🆕 Creando nueva receta');
        await recipeService.createRecipe(formulario);
        onGuardada('✅ Receta creada exitosamente');
      }
    } catch (error: any) {
      console.error('❌ Error:', error);
      setMensajeError('❌ Error: ' + (error.message || 'Error desconocido'));
    } finally {
      setCargando(false);
    }
  };

  const handleChange = (
    e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>
  ) => {
    const { name, value, type } = e.target;

    if (type === 'checkbox') {
      const checked = (e.target as HTMLInputElement).checked;
      setFormulario({ ...formulario, [name]: checked });
    } else if (type === 'number') {
      setFormulario({ ...formulario, [name]: parseFloat(value) || 0 });
    } else {
      setFormulario({ ...formulario, [name]: value });
    }
  };

  return (
    <form onSubmit={alEnviar}>
      {/* Título */}
      <div className="mb-3">
        <label className="form-label">Título *</label>
        <input
          type="text"
          className="form-control"
          name="title"
          value={formulario.title || ''}
          onChange={handleChange}
        />
        {erroresValidacion.title && (
          <div className="form-text text-danger">{erroresValidacion.title}</div>
        )}
      </div>

      {/* Descripción */}
      <div className="mb-3">
        <label className="form-label">Descripción *</label>
        <textarea
          className="form-control"
          name="description"
          rows={2}
          value={formulario.description || ''}
          onChange={handleChange}
        />
        {erroresValidacion.description && (
          <div className="form-text text-danger">{erroresValidacion.description}</div>
        )}
      </div>

      {/* Ingredientes */}
      <div className="mb-3">
        <label className="form-label">Ingredientes *</label>
        <textarea
          className="form-control"
          name="ingredients"
          rows={2}
          value={formulario.ingredients || ''}
          onChange={handleChange}
        />
        {erroresValidacion.ingredients && (
          <div className="form-text text-danger">{erroresValidacion.ingredients}</div>
        )}
      </div>

      {/* Row: Tiempo y Porciones */}
      <div className="row">
        <div className="col-md-6">
          <div className="mb-3">
            <label className="form-label">Tiempo de Preparación (min) *</label>
            <input
              type="number"
              className="form-control"
              name="preparationTime"
              min="1"
              max="1000"
              value={formulario.preparationTime || ''}
              onChange={handleChange}
            />
            {erroresValidacion.preparationTime && (
              <div className="form-text text-danger">{erroresValidacion.preparationTime}</div>
            )}
          </div>
        </div>
        <div className="col-md-6">
          <div className="mb-3">
            <label className="form-label">Porciones *</label>
            <input
              type="number"
              className="form-control"
              name="servings"
              min="1"
              value={formulario.servings || ''}
              onChange={handleChange}
            />
            {erroresValidacion.servings && (
              <div className="form-text text-danger">{erroresValidacion.servings}</div>
            )}
          </div>
        </div>
      </div>

      {/* Row: Dificultad y Categoría */}
      <div className="row">
        <div className="col-md-6">
          <div className="mb-3">
            <label className="form-label">Dificultad *</label>
            <select
              className="form-select"
              name="difficulty"
              value={formulario.difficulty || ''}
              onChange={handleChange}
            >
              <option value="">Seleccionar</option>
              <option value="easy">Fácil</option>
              <option value="medium">Media</option>
              <option value="hard">Difícil</option>
            </select>
          </div>
        </div>
        <div className="col-md-6">
          <div className="mb-3">
            <label className="form-label">Categoría *</label>
            <select
              className="form-select"
              name="category"
              value={formulario.category || ''}
              onChange={handleChange}
            >
              <option value="">Seleccionar</option>
              <option value="entrante">Entrante</option>
              <option value="principal">Principal</option>
              <option value="postre">Postre</option>
              <option value="bebida">Bebida</option>
              <option value="refrigerio">Refrigerio</option>
            </select>
            {erroresValidacion.category && (
              <div className="form-text text-danger">{erroresValidacion.category}</div>
            )}
          </div>
        </div>
      </div>

      {/* Row: Rating y ImageUrl */}
      <div className="row">
        <div className="col-md-6">
          <div className="mb-3">
            <label className="form-label">Rating (0-5)</label>
            <input
              type="number"
              className="form-control"
              name="rating"
              min="0"
              max="5"
              step="0.1"
              value={formulario.rating || ''}
              onChange={handleChange}
            />
            {erroresValidacion.rating && (
              <div className="form-text text-danger">{erroresValidacion.rating}</div>
            )}
          </div>
        </div>
        <div className="col-md-6">
          <div className="mb-3">
            <label className="form-label">URL de Imagen</label>
            <input
              type="url"
              className="form-control"
              name="imageUrl"
              placeholder="https://ejemplo.com/imagen.jpg"
              value={formulario.imageUrl || ''}
              onChange={handleChange}
            />
          </div>
        </div>
      </div>

      {/* Checkboxes */}
      <div className="form-check mb-3">
        <input
          type="checkbox"
          className="form-check-input"
          id="isVegan"
          name="isVegan"
          checked={formulario.isVegan || false}
          onChange={handleChange}
        />
        <label className="form-check-label" htmlFor="isVegan">
          🌱 Es vegana
        </label>
      </div>

      <div className="form-check mb-3">
        <input
          type="checkbox"
          className="form-check-input"
          id="isGlutenFree"
          name="isGlutenFree"
          checked={formulario.isGlutenFree || false}
          onChange={handleChange}
        />
        <label className="form-check-label" htmlFor="isGlutenFree">
          🚫 Sin gluten
        </label>
      </div>

      {/* Alerta Error */}
      {mensajeError && (
        <div className="alert alert-danger alert-dismissible fade show" role="alert">
          {mensajeError}
          <button
            type="button"
            className="btn-close"
            onClick={() => setMensajeError(null)}
          ></button>
        </div>
      )}

      {/* Botones */}
      <div className="d-flex gap-2">
        <button type="submit" className="btn btn-primary flex-grow-1" disabled={cargando}>
          {cargando ? '⏳ Guardando...' : '💾 Guardar'}
        </button>
        <button type="button" className="btn btn-secondary flex-grow-1" onClick={onCerrada}>
          ❌ Cancelar
        </button>
      </div>
    </form>
  );
};

// frontend-angular/src/app/components/formulario-receta/formulario-receta.component.ts
import { Component, Input, Output, EventEmitter, OnInit, ChangeDetectorRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule, FormBuilder, FormGroup, Validators } from '@angular/forms';
import { RecipeService } from '../../services/recipe.service';
import { Recipe } from '../../models/recipe.model';

@Component({
  selector: 'app-formulario-receta',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule],
  templateUrl: './formulario-receta.component.html',
  styleUrls: ['./formulario-receta.component.css']
})
export class FormularioRecetaComponent implements OnInit {
  @Output() guardada = new EventEmitter<string>();
  @Output() cerrada = new EventEmitter<void>();

  private _receta: Recipe | null = null;
  
  @Input() set receta(value: Recipe | null) {
    console.log('📥 @Input receta cambió:', value);
    this._receta = value;
    
    // Si tenemos receta y el formulario ya está inicializado, precargar datos
    if (this.formulario && this._receta && this._receta._id) {
      console.log('✏️ Precargando datos de receta en el setter');
      this.precargarReceta();
    } else if (this.formulario && !this._receta) {
      // Si NO hay receta (modo crear), resetear formulario
      console.log('🆕 Reseteando formulario para crear nueva receta');
      this.formulario.reset({
        title: '',
        description: '',
        ingredients: '',
        preparationTime: '',
        servings: '',
        difficulty: 'medium',
        category: '',
        isVegan: false,
        isGlutenFree: false,
        rating: 0,
        imageUrl: ''
      });
      this.esEdicion = false;
      this.cdr.detectChanges();
    }
  }
  
  get receta(): Recipe | null {
    return this._receta;
  }

  formulario!: FormGroup;
  cargando = false;
  mensajeError: string | null = null;
  esEdicion = false;

  constructor(private fb: FormBuilder, private recipeService: RecipeService, private cdr: ChangeDetectorRef) {
    this.inicializarFormulario();
  }

  ngOnInit() {
    console.log('📝 FormularioRecetaComponent ngOnInit iniciado');
    
    // Si ya tenemos receta en ngOnInit, precargar
    if (this.receta && this.receta._id) {
      console.log('✏️ Precargando en ngOnInit');
      this.precargarReceta();
    } else {
      console.log('🆕 Modo CREAR nueva receta');
      this.esEdicion = false;
    }
  }

  private precargarReceta() {
    if (!this.receta || !this.receta._id) return;
    
    this.esEdicion = true;
    console.log('Valores de receta a precargar:', this.receta);
    
    const valoresReceta = {
      title: this.receta.title || '',
      description: this.receta.description || '',
      ingredients: this.receta.ingredients || '',
      preparationTime: this.receta.preparationTime || 0,
      servings: this.receta.servings || 1,
      difficulty: this.receta.difficulty || 'medium',
      category: this.receta.category || '',
      isVegan: this.receta.isVegan || false,
      isGlutenFree: this.receta.isGlutenFree || false,
      rating: this.receta.rating || 0,
      imageUrl: this.receta.imageUrl || ''
    };
    
    console.log('Parchando formulario con:', valoresReceta);
    this.formulario.patchValue(valoresReceta);
    this.cdr.detectChanges();
    console.log('✅ Formulario parchado y detectados cambios');
  }

  private inicializarFormulario() {
    this.formulario = this.fb.group({
      title: ['', [Validators.required, Validators.minLength(3)]],
      description: ['', [Validators.required, Validators.minLength(10)]],
      ingredients: ['', Validators.required],
      preparationTime: ['', [Validators.required, Validators.min(1), Validators.max(1000)]],
      servings: ['', [Validators.required, Validators.min(1)]],
      difficulty: ['medium', Validators.required],
      category: ['', Validators.required],
      isVegan: [false],
      isGlutenFree: [false],
      rating: [0, [Validators.min(0), Validators.max(5)]],
      imageUrl: ['']
    });
  }

  alEnviar() {
    if (!this.formulario.valid) {
      this.mensajeError = 'Por favor completa todos los campos correctamente';
      return;
    }

    this.cargando = true;
    this.mensajeError = null;

    if (this.esEdicion && this.receta) {
      this.recipeService.updateRecipe(this.receta._id!, this.formulario.value).subscribe({
        next: (response) => {
          this.cargando = false;
          this.guardada.emit('✅ Receta actualizada exitosamente');
        },
        error: (error) => {
          this.cargando = false;
          this.mensajeError = '❌ Error: ' + (error.error.message || error.message);
        }
      });
    } else {
      this.recipeService.createRecipe(this.formulario.value).subscribe({
        next: (response) => {
          this.cargando = false;
          this.guardada.emit('✅ Receta creada exitosamente');
          this.formulario.reset();
        },
        error: (error) => {
          this.cargando = false;
          this.mensajeError = '❌ Error: ' + (error.error.message || error.message);
        }
      });
    }
  }

  alCancelar() {
    this.cerrada.emit();
  }
}

<form [formGroup]="formulario" (ngSubmit)="alEnviar()">
  <div class="mb-3">
    <label class="form-label">Título *</label>
    <input type="text" class="form-control" formControlName="title" required>
    <div class="form-text text-danger" *ngIf="formulario.get('title')?.hasError('required') && formulario.get('title')?.touched">
      El título es requerido
    </div>
  </div>

  <div class="mb-3">
    <label class="form-label">Descripción *</label>
    <textarea class="form-control" formControlName="description" rows="2" required></textarea>
    <div class="form-text text-danger" *ngIf="formulario.get('description')?.hasError('required') && formulario.get('description')?.touched">
      La descripción es requerida (mín. 10 caracteres)
    </div>
  </div>

  <div class="mb-3">
    <label class="form-label">Ingredientes *</label>
    <textarea class="form-control" formControlName="ingredients" rows="2" required></textarea>
    <div class="form-text text-danger" *ngIf="formulario.get('ingredients')?.hasError('required') && formulario.get('ingredients')?.touched">
      Los ingredientes son requeridos
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <div class="mb-3">
        <label class="form-label">Tiempo de Preparación (min) *</label>
        <input type="number" class="form-control" formControlName="preparationTime" min="1" max="1000" required>
        <div class="form-text text-danger" *ngIf="formulario.get('preparationTime')?.hasError('required') && formulario.get('preparationTime')?.touched">
          Tiempo requerido (1-1000 min)
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="mb-3">
        <label class="form-label">Porciones *</label>
        <input type="number" class="form-control" formControlName="servings" min="1" required>
        <div class="form-text text-danger" *ngIf="formulario.get('servings')?.hasError('required') && formulario.get('servings')?.touched">
          Porciones requeridas
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <div class="mb-3">
        <label class="form-label">Dificultad *</label>
        <select class="form-select" formControlName="difficulty" required>
          <option value="">Seleccionar</option>
          <option value="easy">Fácil</option>
          <option value="medium">Media</option>
          <option value="hard">Difícil</option>
        </select>
      </div>
    </div>
    <div class="col-md-6">
      <div class="mb-3">
        <label class="form-label">Categoría *</label>
        <select class="form-select" formControlName="category" required>
          <option value="">Seleccionar</option>
          <option value="entrante">Entrante</option>
          <option value="principal">Principal</option>
          <option value="postre">Postre</option>
          <option value="bebida">Bebida</option>
          <option value="refrigerio">Refrigerio</option>
        </select>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <div class="mb-3">
        <label class="form-label">Rating (0-5)</label>
        <input type="number" class="form-control" formControlName="rating" min="0" max="5" step="0.1">
      </div>
    </div>
    <div class="col-md-6">
      <div class="mb-3">
        <label class="form-label">URL de Imagen</label>
        <input type="url" class="form-control" formControlName="imageUrl" placeholder="https://ejemplo.com/imagen.jpg">
      </div>
    </div>
  </div>

  <div class="form-check mb-3">
    <input class="form-check-input" type="checkbox" formControlName="isVegan" id="esVegana">
    <label class="form-check-label" for="esVegana">
      Es Vegana 🌱
    </label>
  </div>

  <div class="form-check mb-3">
    <input class="form-check-input" type="checkbox" formControlName="isGlutenFree" id="sinGluten">
    <label class="form-check-label" for="sinGluten">
      Sin Gluten 🌾
    </label>
  </div>

  <div *ngIf="mensajeError" class="alert alert-danger">
    {{ mensajeError }}
  </div>

  <div class="d-flex gap-2">
    <button type="submit" class="btn btn-primary" [disabled]="!formulario.valid || cargando">
      <span *ngIf="cargando" class="spinner-border spinner-border-sm me-2"></span>
      {{ esEdicion ? 'Actualizar' : 'Crear' }}
    </button>
    <button type="button" class="btn btn-secondary" (click)="alCancelar()">Cancelar</button>
  </div>
</form>
